# used as reference - https://github.com/n1tsu/n36tsu
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 8
  py: ky + 8
  # Outline (former 0.5px/py)
  pushX: px / 2
  pushY: py / 2
  # former 0.25px/py
  halfPushX: pushX / 2
  halfPushY: pushY / 2
  # former 0.125px/py
  quartPushX: halfPushX / 2
  quartPushY: halfPushY / 2
  # former 0.75px/push
  halfPlusPushX: halfPushX + pushX
  halfPlusPushY: halfPushY + pushY
points:
  zones:
    # The primary 6x5 key matrix, plus 3 modifiers.
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key:
            spread: 1.25kx
        pinky:
        ring:
          key:
            stagger: 0.25ky
        middle:
          key:
            stagger: 0.25ky
        index:
          key:
            stagger: -0.25ky
          # rows:
          #   mod:
          #     width: 2kx
          #     adjust.shift: [kx/2, 0]
        inner:
          key:
            stagger: -0.25ky
      rows:
        bottom:
        home:
        top:
        num:
    thumbs:
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
      # Place thumbs where the inner mod would go.
      anchor:
        ref: matrix_inner_bottom
        shift: [0kx, -1.25ky]
      columns:
        # Fan thumbs out by -15 degrees.
        layer:
          key:
            splay: -25
            column_net: P8
        # Spacebar uses a 1.5 wide key.
        space:
          key:
            width: 1.5kx
            splay: 90
            shift: [-0.25kx, 0]
            column_net: P9
      rows:
        # Thumbs only have one row.
        cluster:
          row_net: P15
          mirror.row_net: P6
  mirror: &mirror
    ref: matrix_inner_num
    distance: 6kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num
          shift: [-pushX, pushY]
        - ref: matrix_ring_num
          shift: [-pushX, pushY]
        - ref: matrix_middle_num
          shift: [-pushX, pushY]
        - ref: matrix_middle_num
          shift: [pushX, pushY]
        - ref: matrix_inner_num
          shift: [pushX, pushY]
        - ref: matrix_inner_top
          shift: [pushX, pushY]
        - ref: matrix_inner_home
          shift: [pushX, pushY]
        - ref: matrix_inner_bottom
          shift: [pushX, -0.125py]
        - ref: matrix_inner_bottom
          shift: [halfPlusPushX, -halfPushY]
        - ref: matrix_inner_bottom
          shift: [halfPlusPushX, -0.875py]
        - ref: matrix_inner_bottom
          shift: [halfPlusPushX, -0.875py]
        - ref: thumbs_space_cluster
          shift: [0.375px, -pushY]
        - ref: thumbs_space_cluster
          shift: [-1px, -pushY]
        - ref: thumbs_space_cluster
          shift: [-1px, 0.400py]
        - ref: thumbs_space_cluster
          shift: [-halfPushX, 0.400py]
        - ref: thumbs_layer_cluster
          shift: [-pushX, -0.425py]
        - ref: matrix_index_bottom
          shift: [0px, -halfPlusPushY]
        - ref: matrix_middle_bottom
          shift: [0px, -0.625py]
        - ref: matrix_ring_bottom
          shift: [-halfPushX, -0.45py]
        - ref: matrix_ring_bottom
          shift: [-halfPushX, -0.67py]
        - ref: matrix_outer_bottom
          shift: [-pushX, -pushY]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_outer_num
          shift: [-pushX, pushY]
        - ref: mirror_matrix_ring_num
          shift: [-pushX, pushY]
        - ref: mirror_matrix_middle_num
          shift: [-pushX, pushY]
        - ref: mirror_matrix_middle_num
          shift: [pushX, pushY]
        - ref: mirror_matrix_inner_num
          shift: [pushX, pushY]
        - ref: mirror_matrix_inner_top
          shift: [pushX, pushY]
        - ref: mirror_matrix_inner_home
          shift: [pushX, pushY]
        - ref: mirror_matrix_inner_bottom
          shift: [pushX, -0.125py]
        - ref: mirror_matrix_inner_bottom
          shift: [halfPlusPushX, -halfPushY]
        - ref: mirror_matrix_inner_bottom
          shift: [halfPlusPushX, -0.875py]
        - ref: mirror_matrix_inner_bottom
          shift: [halfPlusPushX, -0.875py]
        - ref: mirror_thumbs_space_cluster
          shift: [0.375px, -pushY]
        - ref: mirror_thumbs_space_cluster
          shift: [-1px, -pushY]
        - ref: mirror_thumbs_space_cluster
          shift: [-1px, 0.400py]
        - ref: mirror_thumbs_space_cluster
          shift: [-halfPushX, 0.400py]
        - ref: mirror_thumbs_layer_cluster
          shift: [-pushX, -0.425py]
        - ref: mirror_matrix_index_bottom
          shift: [0px, -halfPlusPushY]
        - ref: mirror_matrix_middle_bottom
          shift: [0px, -0.625py]
        - ref: mirror_matrix_ring_bottom
          shift: [-halfPushX, -0.45py]
        - ref: mirror_matrix_ring_bottom
          shift: [-halfPushX, -0.67py]
        - ref: mirror_matrix_outer_bottom
          shift: [-pushX, -pushY]
        # - ref: mirror_matrix_outer_num
        #   shift: [-0.5px, 0.5py]
        # - ref: mirror_matrix_ring_num
        #   shift: [-0.5px, 0.5py]
        # - ref: mirror_matrix_middle_num
        #   shift: [-0.5px, 0.5py]
        # - ref: mirror_matrix_middle_num
        #   shift: [0.5px, 0.5py]
        # - ref: mirror_matrix_inner_num
        #   shift: [0.5px, 0.5py]
        # - ref: mirror_matrix_inner_top
        #   shift: [0.5px, 0.5py]
        # - ref: mirror_matrix_inner_home
        #   shift: [0.5px, 0.5py]
        # - ref: mirror_matrix_inner_bottom
        #   shift: [0.5px, -0.125py]
        # - ref: mirror_matrix_inner_bottom
        #   shift: [0.75px, -0.25py]
        # - ref: mirror_matrix_inner_bottom
        #   shift: [0.75px, -0.875py]
        # - ref: mirror_matrix_inner_bottom
        #   shift: [0.75px, -0.875py]
        # - ref: mirror_thumbs_space_cluster
        #   shift: [0.375px, -0.5py]
        # - ref: mirror_thumbs_space_cluster
        #   shift: [-1px, -0.5py]
        # - ref: mirror_thumbs_space_cluster
        #   shift: [-1px, 0.400py]
        # - ref: mirror_thumbs_space_cluster
        #   shift: [-0.25px, 0.400py]
        # - ref: mirror_thumbs_layer_cluster
        #   shift: [-0.5px, -0.425py]
        # - ref: mirror_matrix_index_bottom
        #   shift: [0px, -0.75py]
        # - ref: mirror_matrix_middle_bottom
        #   shift: [0px, -0.625py]
        # - ref: mirror_matrix_ring_bottom
        #   shift: [-0.25px, -0.45py]
        # - ref: mirror_matrix_ring_bottom
        #   shift: [-0.25px, -0.67py]
        # - ref: mirror_matrix_outer_bottom
        #   shift: [-0.5px, -0.5py]

  combo:
    - name: board_left
    - operation: subtract
      name: keys
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      switch:
        what: pg1316s
        where: /^matrix_.*|^thumbs_.*/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123
        where: /^matrix_.*|^thumbs_.*/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_outer_num
          shift: [5, 1]
          rotate: 0
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      switch:
        what: pg1316s
        where: /^mirror_matrix_.*|^mirror_thumbs_.*/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123
        where: /^mirror_matrix_.*|^mirror_thumbs_.*/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_outer_num
          shift: [5, 1]
          rotate: 180
# cases:
#   plate:
#     - name: xl_board_key_cutouts
#       extrude: 1.2
